version: "2"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./keycloak-data:/opt/keycloak/data/h2/
    ports:
      - "8080:8080"
    command:
      - "start-dev"